### ISSUE TITLE
About New Visualization Issues

### ISSUE THREAD

**Issue by wangxin-fighting** [rohban-lab/Knowledge_Distillation_AD#17]
Hello, I went to test.py to generate a visualization of the anomaly localization after the training, following the closed way that others have asked you before, and I got the following error.What is the reason for this?Looking forward to your reply very much, thank you!

Traceback (most recent call last):
  File "D:/1-study/2-code/Knowledge_Distillation_AD-main/test.py", line 31, in <module>
    main()
  File "D:/1-study/2-code/Knowledge_Distillation_AD-main/test.py", line 20, in main
    config=config)
  File "D:\1-study\2-code\Knowledge_Distillation_AD-main\test_functions.py", line 79, in localization_test
    return compute_localization_auc(grad, ground_truth)
  File "D:\1-study\2-code\Knowledge_Distillation_AD-main\test_functions.py", line 344, in compute_localization_auc
    tp_map = np.multiply(grad_t, x_ground_comp)
ValueError: operands could not be broadcast together with shapes (167,128,128) (141,128,128)

**Comment by SMSD75** [comment]
Hi, Probably the number of GT masks is not the same as the number of training images.
